development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: blog_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: blog_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock


# development:
#   adapter: postgresql
#   encoding: unicode
#   database: blog_development
#   pool: 5
#   password: password

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: blog_test
#   pool: 5
#   password: password

production:
  adapter: postgresql
  encoding: unicode
  database: blog_production
  pool: 5
  password: password
